# Generated by Django 4.1.3 on 2022-12-22 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fanart.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("webtoon", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="fanart/resize/")),
            ],
        ),
        migrations.CreateModel(
            name="Fanart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FanartImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hint_image",
                    models.ImageField(upload_to=fanart.models.UploadTo.save_path),
                ),
                ("result_image", models.ImageField(upload_to="fanart/result/")),
                (
                    "resize_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fanart.baseimage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FanartComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fanart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_set",
                        to="fanart.fanart",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fanart",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fanart.fanartimage"
            ),
        ),
        migrations.AddField(
            model_name="fanart",
            name="likes",
            field=models.ManyToManyField(
                related_name="user_fanart_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="fanart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="fanart",
            name="webtoon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="webtoon.webtoon"
            ),
        ),
    ]
