# Generated by Django 4.1.3 on 2022-12-07 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fanart.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fanart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanartimage',
            name='hint_image',
            field=models.ImageField(upload_to=fanart.models.UploadTo.save_path),
        ),
        migrations.CreateModel(
            name='FanartComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fanart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanart.fanart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
