# Generated by Django 4.1.3 on 2022-12-22 07:50

from django.db import migrations, models
import fanart.models


class Migration(migrations.Migration):

    dependencies = [
        ("fanart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fanartimage",
            name="hint_image",
            field=models.ImageField(upload_to=fanart.models.UploadTo.save_path),
        ),
    ]
