# Generated by Django 4.1.3 on 2022-12-08 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fanart.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fanart', '0002_alter_fanartimage_hint_image_fanartcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanart',
            name='likes',
            field=models.ManyToManyField(related_name='user_fanart_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fanartcomment',
            name='fanart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='fanart.fanart'),
        ),
        migrations.AlterField(
            model_name='fanartimage',
            name='hint_image',
            field=models.ImageField(upload_to=fanart.models.UploadTo.save_path),
        ),
    ]
