# Generated by Django 4.1.3 on 2022-12-08 11:24

from django.db import migrations, models
import fanart.models


class Migration(migrations.Migration):

    dependencies = [
        ('fanart', '0003_alter_fanart_likes_alter_fanartcomment_fanart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanartimage',
            name='hint_image',
            field=models.ImageField(upload_to=fanart.models.UploadTo.save_path),
        ),
    ]
