# Generated by Django 4.1.3 on 2022-12-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
