# Generated by Django 4.1.3 on 2022-12-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                default="mdedia/basicprofileimage.png",
                max_length=255,
                null=True,
                upload_to="user/",
            ),
        ),
    ]
