# Generated by Django 4.1.3 on 2022-12-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="BoardCategory",
        ),
    ]
