# Generated by Django 4.1.3 on 2022-12-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="BoardCategory",
        ),
        migrations.RemoveField(
            model_name="board",
            name="image",
        ),
    ]
