# Generated by Django 4.1.3 on 2022-12-14 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Webtoon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=20)),
                ("author", models.CharField(max_length=30)),
                ("image_url", models.CharField(max_length=60)),
                ("summary", models.TextField()),
                ("genre", models.CharField(max_length=20)),
                ("day_of_the_week", models.CharField(max_length=10)),
                ("webtoon_link", models.CharField(max_length=100)),
                (
                    "webtoon_bookmarks",
                    models.ManyToManyField(
                        related_name="webtoon_bookmarks_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "webtoon_likes",
                    models.ManyToManyField(
                        related_name="webtoon_likes_set", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebtoonComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "webtoon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webtoon_comment_set",
                        to="webtoon.webtoon",
                    ),
                ),
            ],
        ),
    ]
