# Generated by Django 4.1.3 on 2022-12-06 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0002_webtooncomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtooncomment',
            name='webtoon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webtoon_comment_set', to='webtoon.webtoon'),
        ),
    ]
