# Generated by Django 4.1.3 on 2022-12-09 00:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("webtoon", "0003_alter_webtooncomment_webtoon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webtoon",
            name="webtoon_bookmarks",
            field=models.ManyToManyField(
                related_name="webtoon_bookmarks_set", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="webtoon",
            name="webtoon_likes",
            field=models.ManyToManyField(
                related_name="webtoon_likes_set", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
